### ISSUE TITLE
[Question]Later versions??(1.17 later)

### ISSUE THREAD

**Issue by tankyap** [Lucxjo/Kontrolo-Forge#1]
Is there some later versions `(1.17-1.18.2)` for this mod? If yes pls make it. Thanks.

**Comment by Lucxjo** [comment]
There is for the Fabric modloader but not for Forge at the moment. I will take a look at the possibility of updating this project in the upcoming weeks. 

In the meantime, you can use the following links for the Fabric version if you'd like:

- [GitHub](https://github.com/Lucxjo/Kontrolo-Fabric)
- [Modrinth](https://modrinth.com/mod/kontrolo)
- [Curse](https://www.curseforge.com/minecraft/mc-mods/kontrolo)

**Comment by tankyap** [comment]
ok thanks for that

**Comment by Lucxjo** [comment]
Forge versions for both 1.17.1 and 1.18 are now available from [GitHub releases](https://github.com/Lucxjo/Kontrolo-Forge/releases) and [Modrinth](https://modrinth.com/mod/kontrolo-forge/versions). I'm waiting for CurseForge to approve the versions but they will be available [here](https://www.curseforge.com/minecraft/mc-mods/kontrolo-forge/files)

Any issues, please open a new issue and I'll look into it

**Comment by tankyap** [comment]
Ay, thanks.Sry for late reply
